"use client";

import { useState } from "react";
import type { FunnelAnalytics, FunnelStep } from "../data/mock";
import { useAccount, useMockData } from "../lib/account-context";

type FunnelDraft = { name: string; description: string; goal: string; steps: Array<{ name: string; path: string }> };
const defaultDraft: FunnelDraft = { name: "", description: "", goal: "conversion", steps: [{ name: "Landing page", path: "/" }, { name: "Conversion", path: "/success" }] };

function draftFromFunnel(funnel: FunnelAnalytics): FunnelDraft { return { name: funnel.name, description: funnel.description, goal: "conversion", steps: funnel.steps.map((step) => ({ name: step.name, path: step.path })) }; }
function validateDraft(draft: FunnelDraft) { const errors: string[] = []; if (draft.name.trim().length < 2) errors.push("Enter a funnel name."); if (draft.steps.length < 2) errors.push("Add at least two funnel steps."); if (draft.steps.some((step) => !step.name.trim() || !step.path.trim())) errors.push("Every step needs a name and path."); if (new Set(draft.steps.map((step) => step.path.trim())).size !== draft.steps.length) errors.push("Each funnel step must use a unique path."); if (!draft.goal) errors.push("Select a conversion goal."); return errors; }

export function FunnelsView({ funnels, live = false }: Readonly<{ funnels: FunnelAnalytics[]; live?: boolean }>) {
  const account = useAccount();
  const [selectedId, setSelectedId] = useState(funnels[0]?.id ?? "");
  const [items, setItems] = useState(funnels);
  const [editorOpen, setEditorOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const selected = items.find((funnel) => funnel.id === selectedId) ?? items[0];
  if (!selected) return null;
  const canEdit = useMockData || ["OWNER", "ADMIN", "DEVELOPER"].includes(account.selectedOrganization?.role ?? "");
  function openEditor(funnel?: FunnelAnalytics) { setNotice(null); setEditingId(funnel?.id ?? null); setEditorOpen(true); }
  function saveDraft(draft: FunnelDraft) { if (live) { setNotice("Funnel persistence is not connected yet. The backend must store funnel definitions before live changes can be saved."); return; } const errors = validateDraft(draft); if (errors.length) { setNotice(errors.join(" ")); return; } const steps: FunnelStep[] = draft.steps.map((step, index) => ({ name: step.name.trim(), path: step.path.trim(), visitors: index === 0 ? "0" : "—", count: index === 0 ? 100 : 0, conversion: index === 0 ? "100%" : "—", dropOff: index === 0 ? "—" : "—" })); const next: FunnelAnalytics = { id: editingId ?? `funnel-${Date.now()}`, name: draft.name.trim(), description: draft.description.trim() || "Custom conversion journey", totalVisitors: "0", conversions: "0", conversionRate: "0%", change: "—", steps, explanation: { title: "Not enough data yet", reason: "This funnel will show drop-off evidence after matching events are received.", confidence: "—", recommendation: "Collect enough traffic to identify the largest conversion leak.", impact: "Not available" } }; setItems((current) => editingId ? current.map((item) => item.id === editingId ? next : item) : [...current, next]); setSelectedId(next.id); setEditorOpen(false); setNotice("Funnel saved in demo mode."); }
  function archiveSelected() { if (live) { setNotice("Funnel archiving is unavailable until backend funnel persistence is connected."); return; } setItems((current) => current.filter((item) => item.id !== selected.id)); setSelectedId(items.find((item) => item.id !== selected.id)?.id ?? ""); setNotice("Funnel archived in demo mode."); }

  return <div className="funnels-explorer"><div className="funnel-toolbar"><div><p className="eyebrow">Funnel configuration</p><h2>{items.length} tracked funnels</h2></div><button className="button button-dark" disabled={!canEdit} onClick={() => openEditor()} type="button">＋ Create funnel</button></div>{notice && <p className="form-error funnel-notice" role="status">{notice}</p>}<div className="funnel-tabs" role="tablist" aria-label="Funnels"><span className="tab-label">Tracked funnels</span>{items.map((funnel) => <button className={funnel.id === selected.id ? "form-tab active" : "form-tab"} key={funnel.id} onClick={() => setSelectedId(funnel.id)} type="button" role="tab" aria-selected={funnel.id === selected.id}>{funnel.name}</button>)}</div><section className="funnel-summary"><div><p className="eyebrow">{selected.description}</p><h2>{selected.name}</h2></div><div className="funnel-summary-metrics"><div><span>Visitors</span><strong>{selected.totalVisitors}</strong></div><div><span>Conversions</span><strong>{selected.conversions}</strong></div><div><span>Conversion rate</span><strong>{selected.conversionRate}</strong><b>{selected.change}</b></div></div></section><div className="funnel-content-grid"><FunnelSteps funnel={selected} onEdit={() => openEditor(selected)} canEdit={canEdit} /><FunnelExplanation explanation={selected.explanation} /></div><div className="funnel-bottom-grid"><SegmentComparison live={live} /><DropoffSummary funnel={selected} /><div className="funnel-management"><button className="button" disabled={!canEdit} onClick={() => openEditor(selected)} type="button">Edit funnel</button><button className="button" disabled={!canEdit} onClick={archiveSelected} type="button">Archive funnel</button></div></div>{editorOpen && <FunnelEditor draft={editingId ? draftFromFunnel(selected) : defaultDraft} onCancel={() => setEditorOpen(false)} onSave={saveDraft} canEdit={canEdit} />}</div>;
}

function FunnelSteps({ funnel, onEdit, canEdit }: Readonly<{ funnel: FunnelAnalytics; onEdit: () => void; canEdit: boolean }>) {
  return <section className="widget funnel-steps-widget" aria-labelledby="funnel-steps-heading"><div className="widget-heading"><div><p className="eyebrow">Journey analysis</p><h2 id="funnel-steps-heading">Conversion funnel</h2></div><button className="text-action" disabled={!canEdit} onClick={onEdit} type="button">Edit funnel</button></div><div className="funnel-steps">{funnel.steps.map((step, index) => <div className="funnel-step" key={`${step.name}-${index}`}><div className="funnel-step-heading"><span className="step-number">{index + 1}</span><div><strong>{step.name}</strong><span>{step.path}</span></div><b>{step.visitors}</b></div><div className="step-track"><i style={{ width: `${step.count}%` }} /></div><div className="step-meta"><span>{step.conversion} of previous step</span>{step.dropOff !== "—" && <span className={step.dropOff.startsWith("6") ? "dropoff-high" : ""}>↓ {step.dropOff} drop-off</span>}</div>{step.issue && <span className="step-issue">⚑ {step.issue} is a bottleneck</span>}</div>)}</div></section>;
}

function FunnelExplanation({ explanation }: Readonly<{ explanation: FunnelAnalytics["explanation"] }>) {
  return <section className="funnel-explanation" aria-labelledby="funnel-explanation-heading"><div className="recommendation-top"><span className="priority priority-high">AI analysis</span><span className="recommendation-spark">✦</span></div><p className="eyebrow">Why visitors leave</p><h2 id="funnel-explanation-heading">{explanation.title}</h2><p className="recommendation-reason">{explanation.reason}</p><div className="confidence-row"><span>Confidence</span><strong>{explanation.confidence}</strong></div><div className="funnel-next-step"><span>Recommended action</span><p>{explanation.recommendation}</p></div><div className="recommendation-impact"><span>Expected improvement</span><strong>{explanation.impact}</strong></div><button className="button button-dark" type="button">Create action plan →</button></section>;
}

function SegmentComparison({ live = false }: Readonly<{ live?: boolean }>) {
  if (live) return <section className="widget segment-widget" aria-labelledby="segment-heading"><div className="widget-heading"><div><p className="eyebrow">Compare behaviour</p><h2 id="segment-heading">Segment performance</h2></div><span className="list-meta">Unavailable</span></div><p className="widget-empty">Segment comparisons will be available when funnel definitions and segment queries are connected.</p></section>;
  return <section className="widget segment-widget" aria-labelledby="segment-heading"><div className="widget-heading"><div><p className="eyebrow">Compare behaviour</p><h2 id="segment-heading">Segment performance</h2></div><span className="list-meta">Demo data</span></div><div className="segment-row"><span className="segment-dot mobile" /><div><strong>Mobile</strong><span>7,824 visitors</span></div><b>2.94%</b><small>−1.87%</small></div><div className="segment-row"><span className="segment-dot desktop" /><div><strong>Desktop</strong><span>5,018 visitors</span></div><b>7.74%</b><small>Baseline</small></div><button className="outline-action" type="button">Add segment comparison +</button></section>;
}

function DropoffSummary({ funnel }: Readonly<{ funnel: FunnelAnalytics }>) {
  const bottlenecks = funnel.steps.filter((step) => step.issue);
  return <section className="widget" aria-labelledby="dropoff-heading"><div className="widget-heading"><div><p className="eyebrow">Prioritize fixes</p><h2 id="dropoff-heading">Largest drop-offs</h2></div><span className="list-meta">By step</span></div><div className="dropoff-list">{bottlenecks.map((step, index) => <div className="dropoff-row" key={step.name}><span>{index + 1}</span><div><strong>{step.name}</strong><p>{step.issue}</p></div><b>{step.dropOff}</b></div>)}</div></section>;
}

function FunnelEditor({ draft: initialDraft, onCancel, onSave, canEdit }: Readonly<{ draft: FunnelDraft; onCancel: () => void; onSave: (draft: FunnelDraft) => void; canEdit: boolean }>) {
  const [draft, setDraft] = useState(initialDraft);
  function updateStep(index: number, field: "name" | "path", value: string) { setDraft((current) => ({ ...current, steps: current.steps.map((step, stepIndex) => stepIndex === index ? { ...step, [field]: value } : step) })); }
  return <div className="funnel-editor-backdrop" role="presentation"><section className="funnel-editor" role="dialog" aria-modal="true" aria-labelledby="funnel-editor-title"><div className="widget-heading"><div><p className="eyebrow">Funnel configuration</p><h2 id="funnel-editor-title">{initialDraft.name ? "Edit funnel" : "Create funnel"}</h2></div><button className="icon-button" onClick={onCancel} type="button" aria-label="Close funnel editor">×</button></div><div className="settings-form"><label>Funnel name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Purchase journey" /></label><label>Conversion goal<select value={draft.goal} onChange={(event) => setDraft({ ...draft, goal: event.target.value })}><option value="conversion">Conversion event</option><option value="form_submit">Form submission</option><option value="purchase">Purchase</option></select></label></div><label className="onboarding-label funnel-description">Description<input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Homepage to completed purchase" /></label><div className="funnel-editor-steps"><div className="widget-heading"><div><p className="eyebrow">Journey steps</p><h3>Define the path</h3></div><button className="button" disabled={draft.steps.length >= 8} onClick={() => setDraft({ ...draft, steps: [...draft.steps, { name: "New step", path: "/new-step" }] })} type="button">＋ Add step</button></div>{draft.steps.map((step, index) => <div className="funnel-editor-step" key={index}><span className="step-number">{index + 1}</span><input aria-label={`Step ${index + 1} name`} value={step.name} onChange={(event) => updateStep(index, "name", event.target.value)} /><input aria-label={`Step ${index + 1} path`} value={step.path} onChange={(event) => updateStep(index, "path", event.target.value)} /><button className="icon-button" disabled={draft.steps.length <= 2} onClick={() => setDraft({ ...draft, steps: draft.steps.filter((_, stepIndex) => stepIndex !== index) })} type="button" aria-label={`Remove step ${index + 1}`}>×</button></div>)}</div><div className="settings-actions"><button className="button" onClick={onCancel} type="button">Cancel</button><button className="button button-dark" disabled={!canEdit} onClick={() => onSave(draft)} type="button">Save funnel</button></div></section></div>;
}
