"use client";

import { useState } from "react";
import type { BehaviourIssue, ClickTarget } from "../data/mock";

const pageOptions = ["All pages", "/", "/pricing", "/features", "/blog/ai-growth"];

export function BehaviourView({ clickTargets, issues, scrollPages, live = false, rows = [], summary, journey = [] }: Readonly<{ clickTargets: ClickTarget[]; issues: BehaviourIssue[]; scrollPages: { page: string; visitors: string; depth: number; fold: number }[]; live?: boolean; rows?: { event_type: string; events: number; visitors: number }[]; summary?: { totalClicks: number; avgScrollDepth: number | null; rageClicks: number; deadClicks: number; scrollEvents: number }; journey?: { landing: string; exit: string; sessions: number }[] }>) {
  const clickCount = rows.find((row) => row.event_type === "click")?.events;
  const [page, setPage] = useState(pageOptions[0]);
  const visibleIssues = page === "All pages" ? issues : issues.filter((issue) => issue.page === page);
  return <div className="behaviour-explorer"><div className="behaviour-toolbar"><div><p className="eyebrow">Interaction analytics</p><h2>What are visitors doing?</h2></div><div className="filters"><select className="select-control" value={page} onChange={(event) => setPage(event.target.value)} aria-label="Filter behaviour by page">{pageOptions.map((option) => <option key={option}>{option}</option>)}</select><span className="date-pill">Live data</span></div></div><section className="behaviour-metrics"><Metric label="Total clicks" value={live ? (summary ? summary.totalClicks.toLocaleString() : "—") : "24,892"} change={live ? "Recorded" : "+14.8%"} /><Metric label="Avg. scroll depth" value={live ? (summary?.avgScrollDepth === null || summary?.avgScrollDepth === undefined ? "—" : `${summary.avgScrollDepth}%`) : "61.4%"} change={live ? "Recorded" : "+3.2%"} /><Metric label="Rage clicks" value={live ? (summary ? summary.rageClicks.toLocaleString() : "—") : "486"} change={live ? "Detected" : "−8.1%"} tone="good" /><Metric label="Dead clicks" value={live ? (summary ? summary.deadClicks.toLocaleString() : "—") : "1,208"} change={live ? "Review" : "+4.6%"} tone="bad" /></section><div className="behaviour-grid"><ClickTargets targets={clickTargets} live={live} /><ScrollDepth pages={scrollPages} live={live} /></div><div className="behaviour-grid bottom-behaviour-grid"><BehaviourIssues issues={visibleIssues} live={live} /><PageJourney live={live} journey={journey} /></div></div>;
}

function Metric({ label, value, change, tone }: Readonly<{ label: string; value: string; change: string; tone?: "good" | "bad" }>) {
  return <article className="behaviour-metric"><span>{label}</span><strong>{value}</strong><b className={tone === "bad" ? "change-bad" : "change-good"}>{change}</b><small>vs. previous period</small></article>;
}

function ClickTargets({ targets, live = false }: Readonly<{ targets: ClickTarget[]; live?: boolean }>) {
  return <section className="widget" aria-labelledby="click-targets-heading"><div className="widget-heading"><div><p className="eyebrow">Click analytics</p><h2 id="click-targets-heading">Top clicked elements</h2></div><button className="text-action" type="button">View heatmap →</button></div>{targets.length ? <div className="click-targets">{targets.map((target, index) => <div className="click-target" key={target.selector}><span className="rank-number">0{index + 1}</span><div><strong>{target.label}</strong><span>{target.selector}</span></div><b>{target.clicks}</b><small>{target.rate}</small>{target.issue && <em>{target.issue}</em>}</div>)}</div> : <p className="widget-empty">{live ? "No click events were recorded." : "No click targets found."}</p>}</section>;
}

function ScrollDepth({ pages, live = false }: Readonly<{ pages: { page: string; visitors: string; depth: number; fold: number }[]; live?: boolean }>) {
  return <section className="widget" aria-labelledby="scroll-depth-heading"><div className="widget-heading"><div><p className="eyebrow">Attention signal</p><h2 id="scroll-depth-heading">Scroll depth by page</h2></div><span className="list-meta">Avg. visitor depth</span></div>{pages.length ? <div className="scroll-list">{pages.map((page) => <div className="scroll-row" key={page.page}><div className="scroll-label"><strong>{page.page}</strong><span>{page.visitors} visitors</span></div><div className="scroll-track"><i style={{ width: `${page.depth}%` }} /><span>{page.depth}%</span></div><small>Fold {page.fold}%</small></div>)}</div> : <p className="widget-empty">{live ? "Scroll-depth tracking is not available yet." : "No scroll pages found."}</p>}</section>;
}

function BehaviourIssues({ issues, live = false }: Readonly<{ issues: BehaviourIssue[]; live?: boolean }>) {
  return <section className="widget" aria-labelledby="behaviour-issues-heading"><div className="widget-heading"><div><p className="eyebrow">UX signals</p><h2 id="behaviour-issues-heading">Issues to investigate</h2></div><span className="list-meta">{issues.length} findings</span></div>{issues.length ? <div className="behaviour-issue-list">{issues.map((issue) => <div className="behaviour-issue" key={issue.title}><span className={`issue-icon issue-${issue.type.toLowerCase().replace(" ", "-")}`}>{issue.type === "Rage click" ? "!" : issue.type === "Dead click" ? "×" : "↕"}</span><div><div className="issue-title"><strong>{issue.title}</strong><span className={`priority priority-${issue.priority.toLowerCase()}`}>{issue.priority}</span></div><p>{issue.page} · {issue.detail}</p><small>Est. impact {issue.impact}</small></div></div>)}</div> : <p className="widget-empty">{live ? "Issue detection will appear after rage-click and dead-click tracking is enabled." : "No issues found."}</p>}</section>;
}

function PageJourney({ live = false, journey = [] }: Readonly<{ live?: boolean; journey?: { landing: string; exit: string; sessions: number }[] }>) {
  if (live) { const landing = journey[0]; const exit = [...journey].sort((a, b) => b.sessions - a.sessions)[0]; return <section className="widget journey-widget" aria-labelledby="journey-heading"><div className="widget-heading"><div><p className="eyebrow">Journey context</p><h2 id="journey-heading">Landing and exit pages</h2></div><span className="list-meta">Live data</span></div>{landing ? <div className="journey-columns"><div><span className="journey-label">Top landing page</span><strong>{landing.landing || "/"}</strong><p>{landing.sessions} sessions</p></div><div><span className="journey-label">Top exit page</span><strong>{exit?.exit || "/"}</strong><p>{exit?.sessions ?? 0} sessions</p></div></div> : <p className="widget-empty">Landing and exit data will appear after session events are recorded.</p>}</section>; }
  return <section className="widget journey-widget" aria-labelledby="journey-heading"><div className="widget-heading"><div><p className="eyebrow">Journey context</p><h2 id="journey-heading">Landing and exit pages</h2></div><span className="list-meta">Last 30 days</span></div><div className="journey-columns"><div><span className="journey-label">Top landing page</span><strong>/pricing</strong><p>6,218 visitors · 48.2% bounce</p><button className="text-action" type="button">Inspect page →</button></div><div><span className="journey-label">Top exit page</span><strong>/checkout</strong><p>1,104 exits · 65.9% drop-off</p><button className="text-action" type="button">Inspect page →</button></div></div><div className="journey-note"><span>✦</span><p>Pricing attracts high-intent visitors, but checkout exits are unusually high for this journey.</p></div></section>;
}
