"use client";

import { useEffect, useState } from "react";
import type { WebsiteSettings } from "../data/mock";
import { createAlertWebhook, createApiKey, createPrivacyRequest, deleteAlertWebhook, dispatchAlerts, exportOrganizationData, getAlertSettings, getApiKeys, getAuditLogs, getPrivacyRequests, getTrackingScript, revokeApiKey, testAlertWebhook, updateAlertPreference, verifyTracking, type AlertEndpoint, type AlertPreference, type ApiKey, type AuditLog, type PrivacyRequest } from "../lib/api-client";
import { useAccount, useMockData } from "../lib/account-context";
import { EmptyState } from "../components/dashboard-shell";
import { ErrorState, LoadingState } from "../components/ui";

const tabs = ["Website", "Installation", "Team", "Billing", "Alerts", "API keys", "Privacy", "Audit log"] as const;
type SettingsTab = (typeof tabs)[number];

export function SettingsView({ website }: Readonly<{ website: WebsiteSettings }>) {
  const account = useAccount();
  const [tab, setTab] = useState<SettingsTab>("Website");
  if (!useMockData && account.isLoading && !account.selectedWebsite && ["Website", "Installation"].includes(tab)) return <LoadingState />;
  if (!useMockData && !account.selectedWebsite && ["Website", "Installation"].includes(tab)) return <ErrorState message={account.error ?? "No website is available in this organization."} onRetry={account.retry} />;
  const liveWebsite = account.selectedWebsite;
  const currentWebsite: WebsiteSettings = liveWebsite ? { ...website, name: liveWebsite.name, domain: liveWebsite.domain, trackingId: liveWebsite.trackingId, timezone: liveWebsite.timezone, currency: liveWebsite.currency, industry: liveWebsite.industry ?? "", status: liveWebsite.installationStatus === "VERIFIED" ? "Connected" : "Needs setup", plan: account.selectedOrganization?.plan ?? website.plan } : website;
  return <div className="settings-explorer"><div className="settings-tabs" role="tablist" aria-label="Settings sections">{tabs.map((item) => <button className={item === tab ? "settings-tab active" : "settings-tab"} key={item} onClick={() => setTab(item)} type="button" role="tab" aria-selected={item === tab}>{item}</button>)}</div>{tab === "Website" && <WebsiteSettingsPanel website={currentWebsite} />}{tab === "Installation" && <InstallationPanel website={currentWebsite} />}{tab === "Team" && <TeamPanel />}{tab === "Billing" && <BillingPanel website={currentWebsite} />}{tab === "Alerts" && <AlertsPanel />}{tab === "API keys" && <ApiKeysPanel />}{tab === "Privacy" && <PrivacyPanel />}{tab === "Audit log" && <AuditLogPanel />}</div>;
}

function WebsiteSettingsPanel({ website }: Readonly<{ website: WebsiteSettings }>) {
  const account = useAccount();
  const [form, setForm] = useState({ name: website.name, domain: website.domain, industry: website.industry, timezone: website.timezone, currency: website.currency });
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  useEffect(() => setForm({ name: website.name, domain: website.domain, industry: website.industry, timezone: website.timezone, currency: website.currency }), [website]);
  async function save() { if (useMockData || !account.selectedWebsite) return; setSaveState("saving"); try { await account.updateSelectedWebsite(form); setSaveState("saved"); } catch { setSaveState("error"); } }
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Website settings</p><h2>Configure your website</h2></div><span className="connected-badge"><i /> {website.status}</span></div><div className="settings-form"><label>Website name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Domain<input value={form.domain} onChange={(event) => setForm({ ...form, domain: event.target.value })} /></label><label>Industry<select value={form.industry} onChange={(event) => setForm({ ...form, industry: event.target.value })}><option value="SaaS / Technology">SaaS / Technology</option><option value="E-commerce">E-commerce</option><option value="Professional services">Professional services</option><option value="Media / Publishing">Media / Publishing</option></select></label><label>Timezone<select value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })}><option>Asia/Kolkata</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select></label><label>Currency<select value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value })}><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option></select></label></div><div className="settings-actions"><button className="button button-dark" disabled={saveState === "saving"} onClick={save} type="button">{saveState === "saving" ? "Saving…" : saveState === "saved" ? "Saved" : "Save changes"}</button><button className="button" type="button">Archive website</button>{saveState === "error" && <span className="form-error">Could not save changes.</span>}</div></div>;
}

function InstallationPanel({ website }: Readonly<{ website: WebsiteSettings }>) {
  const account = useAccount();
  const [snippet, setSnippet] = useState(`<script src="https://app.aigrowth.dev/tracker.js"\n  data-tracking-id="${website.trackingId}"></script>`);
  const [verifyMessage, setVerifyMessage] = useState(website.status === "Connected" ? "Tracking is connected." : "Visit your website after installing the script.");
  const [verificationStatus, setVerificationStatus] = useState(website.status === "Connected" ? "TRACKING_VERIFIED" : "TRACKING_NOT_DETECTED");
  useEffect(() => { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization || !account.selectedWebsite) return; getTrackingScript(account.tokens.accessToken, account.selectedOrganization.id, account.selectedWebsite.id).then((result) => { setSnippet(result.tracking.snippet); setVerificationStatus(result.tracking.installationStatus === "VERIFIED" ? "TRACKING_VERIFIED" : result.tracking.websiteStatus === "PAUSED" ? "TRACKING_PAUSED" : result.tracking.websiteStatus === "ARCHIVED" ? "TRACKING_ARCHIVED" : "TRACKING_NOT_DETECTED"); }).catch(() => setVerifyMessage("Could not load the tracking installation details.")); }, [account.tokens, account.selectedOrganization, account.selectedWebsite]);
  async function verify() { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization || !account.selectedWebsite) return; try { const result = await verifyTracking(account.tokens.accessToken, account.selectedOrganization.id, account.selectedWebsite.id, website.domain); setVerificationStatus(result.status); setVerifyMessage(result.message ?? (result.verified ? "Tracking is connected." : "Tracking has not been detected yet.")); } catch (error) { setVerifyMessage(error instanceof Error ? error.message : "Verification failed."); } }
  const statusLabel = verificationStatus === "TRACKING_VERIFIED" ? "Verified" : verificationStatus === "TRACKING_PAUSED" ? "Paused" : verificationStatus === "TRACKING_ARCHIVED" ? "Archived" : "Needs setup";
  const canVerify = verificationStatus !== "TRACKING_PAUSED" && verificationStatus !== "TRACKING_ARCHIVED";
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Tracking setup</p><h2>Connect {website.domain}</h2></div><span className="connected-badge"><i /> {statusLabel}</span></div><div className="tracking-id-card"><span>Tracking ID</span><strong>{website.trackingId}</strong><button className="copy-button" type="button" onClick={() => void navigator.clipboard?.writeText(website.trackingId)}>Copy</button></div><div className="install-step"><span>1</span><div><h3>Copy this script</h3><p>Add it before the closing <code>&lt;/head&gt;</code> tag on every page. For consent-gated sites, add <code>data-require-consent="true"</code> and call <code>window.aiGrowth.grantConsent()</code> after consent.</p><pre>{snippet}</pre><button className="button" onClick={() => void navigator.clipboard?.writeText(snippet)} type="button">Copy script</button></div></div><div className="install-step"><span>2</span><div><h3>Verify your connection</h3><p>{verifyMessage}</p><button className="button button-dark" disabled={!canVerify} onClick={verify} type="button">{statusLabel === "Verified" ? "Connection verified" : "Check connection"}</button></div></div></div>;
}

function TeamPanel() { return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Organization</p><h2>Team access</h2></div><button className="button button-dark" type="button">＋ Invite member</button></div><div className="team-row"><span className="avatar">MJ</span><div><strong>Mohd Jawed</strong><span>Owner · jawed@example.com</span></div><b>Owner</b></div><div className="team-row"><span className="avatar avatar-muted">AM</span><div><strong>Analytics marketing</strong><span>Viewer access · Invite pending</span></div><b>Pending</b></div><div className="role-note"><span>ⓘ</span><p>Team roles and permissions control access to visitor data, reports, and billing.</p></div></div>; }
function BillingPanel({ website }: Readonly<{ website: WebsiteSettings }>) { return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Subscription</p><h2>Manage your plan</h2></div><span className="plan-badge">{website.plan} plan</span></div><div className="plan-card"><div><strong>Growth</strong><p>For teams ready to turn behaviour into revenue.</p></div><b>$99 <small>/ month</small></b></div><div className="usage-row"><div><span>Monthly events</span><strong>{website.eventsThisMonth} / 100,000</strong></div><div className="usage-track"><i style={{ width: "31%" }} /></div></div><div className="settings-actions"><button className="button button-dark" type="button">Manage subscription</button><button className="button" type="button">View invoices</button></div></div>; }

function AlertsPanel() {
  const account = useAccount();
  const canManage = useMockData || ["OWNER", "ADMIN"].includes(account.selectedOrganization?.role ?? "");
  const [endpoints, setEndpoints] = useState<AlertEndpoint[]>([]);
  const [preference, setPreference] = useState<AlertPreference>({ websiteId: "", enabled: true, minimumPriority: "HIGH" });
  const [name, setName] = useState("");
  const [url, setUrl] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(!useMockData);
  useEffect(() => { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization || !account.selectedWebsite) { setLoading(false); return; } getAlertSettings(account.tokens.accessToken, account.selectedOrganization.id, account.selectedWebsite.id).then((result) => { setEndpoints(result.endpoints); setPreference(result.preference ?? { websiteId: account.selectedWebsite!.id, enabled: true, minimumPriority: "HIGH" }); }).catch(() => setMessage("Could not load alert settings.")).finally(() => setLoading(false)); }, [account.tokens, account.selectedOrganization, account.selectedWebsite]);
  async function addWebhook() { if (!canManage || name.trim().length < 2 || !url.trim()) { setMessage("Enter a webhook name and URL."); return; } if (useMockData) { setMessage("Webhook settings are available in live mode."); return; } if (!account.tokens?.accessToken || !account.selectedOrganization) return; try { const result = await createAlertWebhook(account.tokens.accessToken, account.selectedOrganization.id, name.trim(), url.trim()); setEndpoints((current) => [result.endpoint, ...current]); setName(""); setUrl(""); setMessage("Webhook added."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not add webhook."); } }
  async function savePreference() { if (!canManage || useMockData || !account.tokens?.accessToken || !account.selectedOrganization || !account.selectedWebsite) return; try { const result = await updateAlertPreference(account.tokens.accessToken, account.selectedOrganization.id, account.selectedWebsite.id, { enabled: preference.enabled, minimumPriority: preference.minimumPriority }); setPreference(result.preference); setMessage("Alert preference saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save alert preference."); } }
  async function test(endpoint: AlertEndpoint) { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization) return; try { const result = await testAlertWebhook(account.tokens.accessToken, account.selectedOrganization.id, endpoint.id); setMessage(result.delivery.status === "SENT" ? `${endpoint.name} received the test alert.` : result.delivery.error ?? "Webhook test failed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Webhook test failed."); } }
  async function remove(endpoint: AlertEndpoint) { if (!canManage || useMockData || !account.tokens?.accessToken || !account.selectedOrganization) return; if (!window.confirm(`Delete ${endpoint.name}?`)) return; try { await deleteAlertWebhook(account.tokens.accessToken, account.selectedOrganization.id, endpoint.id); setEndpoints((current) => current.filter((item) => item.id !== endpoint.id)); setMessage("Webhook deleted."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not delete webhook."); } }
  async function dispatch() { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization || !account.selectedWebsite) return; try { const result = await dispatchAlerts(account.tokens.accessToken, account.selectedOrganization.id, account.selectedWebsite.id); setMessage(`${result.dispatched} alert${result.dispatched === 1 ? "" : "s"} delivered.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not dispatch alerts."); } }
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">CRO alerts</p><h2>Alert delivery</h2></div><span className="list-meta">{canManage ? "Owner/admin" : "View only"}</span></div><p className="settings-copy">Send high-priority CRO recommendations to a webhook you control. URLs are encrypted at rest and never displayed after saving.</p>{message && <p className="form-error" role="status">{message}</p>}{loading ? <LoadingState /> : <><div className="alert-preference-row"><label><input type="checkbox" checked={preference.enabled} disabled={!canManage} onChange={(event) => setPreference({ ...preference, enabled: event.target.checked })} /> Enable alerts</label><select value={preference.minimumPriority} disabled={!canManage} onChange={(event) => setPreference({ ...preference, minimumPriority: event.target.value as AlertPreference["minimumPriority"] })} aria-label="Minimum alert priority"><option value="HIGH">High priority only</option><option value="MEDIUM">Medium and high</option><option value="LOW">All priorities</option></select><button className="button" disabled={!canManage || useMockData} onClick={() => void savePreference()} type="button">Save preference</button><button className="button" disabled={useMockData || !preference.enabled} onClick={() => void dispatch()} type="button">Dispatch now</button></div><div className="api-key-create"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Webhook name" aria-label="Webhook name" disabled={!canManage} /><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/webhook" aria-label="Webhook URL" disabled={!canManage} /><button className="button button-dark" disabled={!canManage} onClick={() => void addWebhook()} type="button">Add webhook</button></div>{endpoints.length ? <div className="api-key-list">{endpoints.map((endpoint) => <div className="api-key-row" key={endpoint.id}><div><strong>{endpoint.name}</strong><span>{endpoint.lastDeliveryStatus ? `Last delivery: ${endpoint.lastDeliveryStatus}` : "Not tested yet"}</span></div><span className={endpoint.status === "ACTIVE" ? "insight-status insight-status-open" : "insight-status insight-status-dismissed"}>{endpoint.status}</span><button className="button" disabled={!canManage || endpoint.status !== "ACTIVE"} onClick={() => void test(endpoint)} type="button">Test</button><button className="button" disabled={!canManage} onClick={() => void remove(endpoint)} type="button">Delete</button></div>)}</div> : <p className="widget-empty">No webhook endpoints configured.</p>}</>}</div>;
}

function ApiKeysPanel() {
  const account = useAccount();
  const canManage = useMockData || ["OWNER", "ADMIN"].includes(account.selectedOrganization?.role ?? "");
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [name, setName] = useState("");
  const [secret, setSecret] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(!useMockData);
  useEffect(() => { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization) { setLoading(false); return; } getApiKeys(account.tokens.accessToken, account.selectedOrganization.id).then((result) => setKeys(result.apiKeys)).catch(() => setMessage("Could not load API keys.")).finally(() => setLoading(false)); }, [account.tokens, account.selectedOrganization]);
  async function create() { if (!canManage || name.trim().length < 2) { setMessage("Enter an API key name with at least 2 characters."); return; } if (useMockData) { setSecret("demo_secret_shown_once"); setMessage("Demo secret shown once. Store it securely."); setName(""); return; } if (!account.tokens?.accessToken || !account.selectedOrganization) return; try { const result = await createApiKey(account.tokens.accessToken, account.selectedOrganization.id, name.trim()); setKeys((current) => [result.apiKey, ...current]); setSecret(result.secret); setMessage(result.warning); setName(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create API key."); } }
  async function revoke(key: ApiKey) { if (!canManage || !window.confirm(`Revoke ${key.name}? Existing integrations will stop working.`)) return; if (useMockData) { setKeys((current) => current.map((item) => item.id === key.id ? { ...item, revokedAt: new Date().toISOString() } : item)); return; } if (!account.tokens?.accessToken || !account.selectedOrganization) return; try { await revokeApiKey(account.tokens.accessToken, account.selectedOrganization.id, key.id); setKeys((current) => current.map((item) => item.id === key.id ? { ...item, revokedAt: new Date().toISOString() } : item)); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not revoke API key."); } }
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Developer access</p><h2>API keys</h2></div><span className="list-meta">{canManage ? "Owner/admin" : "View only"}</span></div><p className="settings-copy">API secrets are encrypted at rest and displayed only once after creation.</p>{secret && <div className="secret-reveal" role="alert"><strong>Copy this secret now</strong><code>{secret}</code><button className="button" type="button" onClick={() => void navigator.clipboard?.writeText(secret)}>Copy secret</button></div>}<div className="api-key-create"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Key name, e.g. Production SDK" aria-label="API key name" disabled={!canManage} /><button className="button button-dark" onClick={() => void create()} disabled={!canManage} type="button">Create key</button></div>{message && <p className="form-error" role="status">{message}</p>}{loading ? <LoadingState /> : keys.length ? <div className="api-key-list">{keys.map((key) => <div className="api-key-row" key={key.id}><div><strong>{key.name}</strong><span>{key.keyPrefix} · Created {new Date(key.createdAt).toLocaleDateString()}</span></div><span className={key.revokedAt ? "insight-status insight-status-dismissed" : "insight-status insight-status-open"}>{key.revokedAt ? "Revoked" : "Active"}</span><button className="button" disabled={!canManage || Boolean(key.revokedAt)} onClick={() => void revoke(key)} type="button">Revoke</button></div>)}</div> : <p className="widget-empty">No API keys have been created.</p>}</div>;
}

function PrivacyPanel() {
  const account = useAccount();
  const [requests, setRequests] = useState<PrivacyRequest[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(!useMockData);
  useEffect(() => { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization) { setLoading(false); return; } getPrivacyRequests(account.tokens.accessToken, account.selectedOrganization.id).then((result) => setRequests(result.requests)).catch(() => setMessage("Could not load privacy requests.")).finally(() => setLoading(false)); }, [account.tokens, account.selectedOrganization]);
  async function exportData() { if (useMockData) { setMessage("Demo export is available only in live mode."); return; } if (!account.tokens?.accessToken || !account.selectedOrganization) return; try { const result = await exportOrganizationData(account.tokens.accessToken, account.selectedOrganization.id); const blob = new Blob([JSON.stringify(result.data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `ai-growth-export-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("Export downloaded."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not export data."); } }
  async function request(type: "EXPORT" | "DELETE") { if (type === "DELETE" && !window.confirm("Request deletion of organization data? This action cannot be undone once processed.")) return; if (useMockData) { setMessage(`${type} request is available in live mode.`); return; } if (!account.tokens?.accessToken || !account.selectedOrganization) return; try { const result = await createPrivacyRequest(account.tokens.accessToken, account.selectedOrganization.id, type); setRequests((current) => [result.request, ...current]); setMessage(`${type} request submitted.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not submit privacy request."); } }
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Privacy controls</p><h2>Export and delete data</h2></div></div><p className="settings-copy">Exports include organization configuration and member records. Event deletion and retention jobs are processed according to your documented policy.</p><div className="settings-actions"><button className="button button-dark" onClick={exportData} type="button">Download export</button><button className="button" onClick={() => void request("EXPORT")} type="button">Create export request</button><button className="button button-danger" onClick={() => void request("DELETE")} type="button">Request deletion</button></div>{message && <p className="form-error" role="status">{message}</p>}<h3 className="settings-subheading">Request history</h3>{loading ? <LoadingState /> : requests.length ? <div className="privacy-request-list">{requests.map((item) => <div className="privacy-request-row" key={item.id}><strong>{item.type}</strong><span>{item.status}</span><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</div> : <p className="widget-empty">No privacy requests yet.</p>}<div className="role-note"><span>ⓘ</span><p>Deletion requests require confirmation and are recorded in the organization audit log.</p></div></div>;
}

function AuditLogPanel() {
  const account = useAccount();
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(!useMockData);
  useEffect(() => { if (useMockData || !account.tokens?.accessToken || !account.selectedOrganization) { setLoading(false); return; } getAuditLogs(account.tokens.accessToken, account.selectedOrganization.id).then((result) => setLogs(result.auditLogs)).catch(() => undefined).finally(() => setLoading(false)); }, [account.tokens, account.selectedOrganization]);
  return <div className="settings-panel"><div className="settings-panel-heading"><div><p className="eyebrow">Organization history</p><h2>Audit log</h2></div><span className="list-meta">Last 100 events</span></div>{loading ? <LoadingState /> : logs.length ? <div className="audit-list">{logs.map((log) => <div className="audit-row" key={log.id}><div><strong>{log.action}</strong><span>{log.entityType}{log.entityId ? ` · ${log.entityId}` : ""}</span></div><time>{new Date(log.createdAt).toLocaleString()}</time></div>)}</div> : <p className="widget-empty">No audit events available.</p>}</div>;
}
